on:
  - push
  - pull_request

name: CDDL

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build CDDL
        run: rm -f temp.cddl && find * -iname \*.cddl | xargs cat > temp.cddl
      - uses: docker://ghcr.io/anweiss/cddl-cli:latest
        with:
          args: compile-cddl --cddl /github/workspace/temp.cddl
